import "server-only";
import argon2 from "argon2";
import { createHash } from "node:crypto";
import { getServiceRoleClient } from "@/lib/supabase/service";

/**
 * PIN hashing + verification with backwards-compat migration.
 *
 * New: argon2id, memoryCost 64MB, timeCost 3. Per-user salt is the email
 * + a random salt generated by argon2. Resistance vs GPU cracking is
 * ~5 orders of magnitude better than SHA-256 for 4–6 digit PINs.
 *
 * Legacy: users created before 2026-04-17 have SHA-256 hashes:
 *   sha256(`${pin}:${email.toLowerCase()}`)
 * On verify, we detect the hash format (argon2 hashes start with "$argon2id$";
 * SHA-256 hashes are 64-char hex). If legacy and valid, we re-hash and
 * persist the argon2 version — opportunistic migration, one user per login.
 *
 * Rate limit: caller checks login_attempts table (5 fails / 15 min / email).
 */

const PEPPER = process.env.PIN_PEPPER || "";

function sha256Hash(pin: string, email: string): string {
  return createHash("sha256").update(`${pin}:${email.toLowerCase()}`).digest("hex");
}

function isArgon2Hash(h: string): boolean {
  return typeof h === "string" && h.startsWith("$argon2");
}

export async function hashPin(pin: string, email: string): Promise<string> {
  const material = `${pin}:${email.toLowerCase()}${PEPPER ? ":" + PEPPER : ""}`;
  return argon2.hash(material, {
    type: argon2.argon2id,
    memoryCost: 65536, // 64 MB
    timeCost: 3,
    parallelism: 1,
  });
}

export async function verifyPin(storedHash: string, pin: string, email: string): Promise<boolean> {
  if (!storedHash) return false;
  const normalizedEmail = email.toLowerCase();
  const material = `${pin}:${normalizedEmail}${PEPPER ? ":" + PEPPER : ""}`;
  if (isArgon2Hash(storedHash)) {
    try {
      return await argon2.verify(storedHash, material);
    } catch {
      return false;
    }
  }
  // Legacy SHA-256 — still verify but signal caller to upgrade.
  const legacy = sha256Hash(pin, normalizedEmail);
  return storedHash === legacy;
}

/**
 * Returns { ok, shouldUpgrade } — when legacy hash, caller should re-hash
 * and update the users.pin_hash column to the returned `newHash`.
 */
export async function verifyPinWithUpgrade(
  storedHash: string,
  pin: string,
  email: string,
): Promise<{ ok: boolean; shouldUpgrade: boolean; newHash?: string }> {
  if (!(await verifyPin(storedHash, pin, email))) {
    return { ok: false, shouldUpgrade: false };
  }
  if (isArgon2Hash(storedHash)) return { ok: true, shouldUpgrade: false };
  const newHash = await hashPin(pin, email);
  return { ok: true, shouldUpgrade: true, newHash };
}

/** Brute-force gate: returns true if the email has ≥5 failed attempts in 15 min.
 *
 * Fail-closed (CN-005b): on DB error the function reports LOCKED. Better to
 * inconvenience legit users during a Supabase outage than to leave the PIN
 * brute-force gate open. Alerts via console.error so ops can react. */
export async function isEmailLocked(email: string): Promise<boolean> {
  try {
    const admin = getServiceRoleClient();
    const since = new Date(Date.now() - 15 * 60 * 1000).toISOString();
    const { count, error } = await admin
      .from("login_attempts")
      .select("*", { count: "exact", head: true })
      .eq("email", email.toLowerCase())
      .eq("succeeded", false)
      .gte("created_at", since);
    if (error) {
      console.error("[pin.lockout] DB error — failing closed:", error.message);
      return true;
    }
    return (count ?? 0) >= 5;
  } catch (err) {
    console.error("[pin.lockout] unexpected error — failing closed:", err);
    return true;
  }
}

export async function recordAttempt(email: string, ip: string | null, succeeded: boolean): Promise<void> {
  try {
    const admin = getServiceRoleClient();
    await admin.from("login_attempts").insert({
      email: email.toLowerCase(),
      ip,
      succeeded,
    });
  } catch { /* table may not exist; soft fail */ }
}
