-- ============================================================
-- DILO — Seed Data
-- 17 Skills + 4 Packs
-- ============================================================

INSERT INTO public.skill_catalog (id, name_es, name_en, name_fr, name_it, name_de, description_es, description_en, description_fr, description_it, description_de, icon, category, tools, price_eur, price_usd, price_mxn, price_cop, price_cad, sort_order) VALUES
('msg_whatsapp', 'Mensajería WhatsApp', 'WhatsApp Messaging', 'Messagerie WhatsApp', 'Messaggistica WhatsApp', 'WhatsApp-Nachrichten', 'Envía y lee mensajes de WhatsApp por ti', 'Send and read WhatsApp messages for you', 'Envoie et lit tes messages WhatsApp', 'Invia e legge i messaggi WhatsApp per te', 'Sendet und liest WhatsApp-Nachrichten für dich', '📤', 'messaging', ARRAY['send_whatsapp_message','read_whatsapp_messages','search_whatsapp','schedule_whatsapp_message','get_whatsapp_contacts','auto_reply_whatsapp','send_whatsapp_group','summarize_whatsapp_chat'], 1.99, 1.99, 35, 7900, 2.69, 1),
('msg_telegram', 'Mensajería Telegram', 'Telegram Messaging', 'Messagerie Telegram', 'Messaggistica Telegram', 'Telegram-Nachrichten', 'Envía y lee mensajes de Telegram por ti', 'Send and read Telegram messages for you', 'Envoie et lit tes messages Telegram', 'Invia e legge i messaggi Telegram per te', 'Sendet und liest Telegram-Nachrichten für dich', '✈️', 'messaging', ARRAY['send_telegram_message','read_telegram_messages','telegram_contacts'], 0.99, 0.99, 17, 3900, 1.29, 2),
('writing', 'Redacción Inteligente', 'Smart Writing', 'Rédaction Intelligente', 'Scrittura Intelligente', 'Intelligentes Schreiben', 'Redacta emails, mensajes formales, CV y más', 'Draft emails, formal messages, CVs and more', 'Rédige emails, messages formels, CV et plus', 'Redige email, messaggi formali, CV e altro', 'Verfasst E-Mails, formelle Nachrichten, Lebensläufe und mehr', '✍️', 'productivity', ARRAY['draft_message','improve_text','formal_tone','correct_grammar'], 1.49, 1.49, 27, 5900, 1.99, 3),
('reminders', 'Recordatorios Pro', 'Pro Reminders', 'Rappels Pro', 'Promemoria Pro', 'Erinnerungen Pro', 'Recordatorios por WhatsApp, múltiples alertas, recurrentes', 'Reminders via WhatsApp, multiple alerts, recurring', 'Rappels via WhatsApp, alertes multiples, récurrents', 'Promemoria via WhatsApp, avvisi multipli, ricorrenti', 'Erinnerungen via WhatsApp, mehrere Benachrichtigungen, wiederkehrend', '⏰', 'productivity', ARRAY['create_reminder_multi','recurring_reminder','remind_other_person','smart_reminder'], 0.99, 0.99, 17, 3900, 1.29, 4),
('finance', 'Finanzas Personales', 'Personal Finance', 'Finances Personnelles', 'Finanze Personali', 'Persönliche Finanzen', 'Controla gastos, presupuesto, divide cuentas', 'Track expenses, budget, split bills', 'Suis tes dépenses, budget, partage les additions', 'Traccia spese, budget, dividi i conti', 'Verfolge Ausgaben, Budget, teile Rechnungen', '💰', 'finance', ARRAY['track_expense','get_expense_summary','set_budget','split_bill','track_subscriptions'], 1.49, 1.49, 27, 5900, 1.99, 5),
('lists', 'Listas y Tareas', 'Lists & Tasks', 'Listes et Tâches', 'Liste e Attività', 'Listen & Aufgaben', 'Listas de compra, tareas, checklists', 'Shopping lists, tasks, checklists', 'Listes de courses, tâches, checklists', 'Liste della spesa, attività, checklist', 'Einkaufslisten, Aufgaben, Checklisten', '📋', 'productivity', ARRAY['create_list','add_to_list','check_item','get_list','share_list','clear_list'], 0.99, 0.99, 17, 3900, 1.29, 6),
('voice', 'Voz Premium', 'Premium Voice', 'Voix Premium', 'Voce Premium', 'Premium-Stimme', 'Input de voz ilimitado, transcripción de audios', 'Unlimited voice input, audio transcription', 'Entrée vocale illimitée, transcription audio', 'Input vocale illimitato, trascrizione audio', 'Unbegrenzte Spracheingabe, Audio-Transkription', '🎤', 'premium', ARRAY['unlimited_voice_input','transcribe_whatsapp_audio','voice_notes'], 1.99, 1.99, 35, 7900, 2.69, 7),
('translator', 'Traductor Pro', 'Pro Translator', 'Traducteur Pro', 'Traduttore Pro', 'Übersetzer Pro', 'Traducciones ilimitadas, traducir y enviar', 'Unlimited translations, translate and send', 'Traductions illimitées, traduire et envoyer', 'Traduzioni illimitate, traduci e invia', 'Unbegrenzte Übersetzungen, übersetzen und senden', '🌍', 'education', ARRAY['translate_text','translate_and_send','detect_language','daily_vocabulary'], 1.49, 1.49, 27, 5900, 1.99, 8),
('tutor', 'Tutor de Idiomas', 'Language Tutor', 'Tuteur de Langues', 'Tutor di Lingue', 'Sprachtutor', 'Practica idiomas con conversación y corrección', 'Practice languages with conversation and correction', 'Pratique les langues avec conversation et correction', 'Pratica le lingue con conversazione e correzione', 'Übe Sprachen mit Konversation und Korrektur', '🎓', 'education', ARRAY['language_practice','correction_feedback','daily_vocab','flashcard_quiz'], 2.99, 2.99, 53, 11900, 3.99, 9),
('health', 'Salud y Bienestar', 'Health & Wellness', 'Santé et Bien-être', 'Salute e Benessere', 'Gesundheit & Wohlbefinden', 'Medicación, hábitos, agua, peso, ejercicio', 'Medication, habits, water, weight, exercise', 'Médicaments, habitudes, eau, poids, exercice', 'Farmaci, abitudini, acqua, peso, esercizio', 'Medikamente, Gewohnheiten, Wasser, Gewicht, Bewegung', '🏥', 'health', ARRAY['medication_reminder','habit_tracker','water_tracker','weight_log','exercise_suggestion'], 1.49, 1.49, 27, 5900, 1.99, 10),
('family', 'Familia y Niños', 'Family & Kids', 'Famille et Enfants', 'Famiglia e Bambini', 'Familie & Kinder', 'Cuentos, actividades por edad, menú infantil', 'Stories, age-based activities, kids menu', 'Histoires, activités par âge, menu enfant', 'Storie, attività per età, menù bambini', 'Geschichten, altersgerechte Aktivitäten, Kindermenü', '👶', 'family', ARRAY['bedtime_story','activity_by_age','kids_menu','homework_help'], 1.49, 1.49, 27, 5900, 1.99, 11),
('travel', 'Viajes', 'Travel', 'Voyages', 'Viaggi', 'Reisen', 'Planifica viajes, itinerarios, maleta, frases', 'Plan trips, itineraries, packing, phrases', 'Planifie tes voyages, itinéraires, valise, phrases', 'Pianifica viaggi, itinerari, valigia, frasi', 'Plane Reisen, Routen, Packliste, Redewendungen', '✈️', 'lifestyle', ARRAY['plan_trip','packing_list','useful_phrases','travel_budget','itinerary'], 1.49, 1.49, 27, 5900, 1.99, 12),
('productivity', 'Productividad Pro', 'Pro Productivity', 'Productivité Pro', 'Produttività Pro', 'Produktivität Pro', 'Briefing matutino, resumen semanal, pomodoro, diario', 'Morning briefing, weekly summary, pomodoro, journal', 'Briefing matinal, résumé hebdo, pomodoro, journal', 'Briefing mattutino, riepilogo settimanale, pomodoro, diario', 'Morgen-Briefing, Wochenübersicht, Pomodoro, Tagebuch', '💼', 'productivity', ARRAY['morning_briefing','weekly_summary','pomodoro_start','decision_helper','journal_entry'], 1.49, 1.49, 27, 5900, 1.99, 13),
('legal', 'Legal Básico', 'Basic Legal', 'Juridique Basic', 'Legale Base', 'Recht Basis', 'Consultas legales básicas, reclamaciones, derechos', 'Basic legal queries, complaints, rights', 'Consultations juridiques basiques, réclamations, droits', 'Consulenze legali base, reclami, diritti', 'Einfache Rechtsberatung, Beschwerden, Rechte', '⚖️', 'professional', ARRAY['legal_query','draft_complaint','check_rights','calculate_deadline'], 1.99, 1.99, 35, 7900, 2.69, 14),
('ai_advanced', 'AI Avanzada', 'Advanced AI', 'IA Avancée', 'AI Avanzata', 'Erweiterte KI', 'Claude Sonnet para respuestas más inteligentes', 'Claude Sonnet for smarter responses', 'Claude Sonnet pour des réponses plus intelligentes', 'Claude Sonnet per risposte più intelligenti', 'Claude Sonnet für intelligentere Antworten', '🧠', 'premium', ARRAY['use_sonnet_model'], 2.99, 2.99, 53, 11900, 3.99, 15),
('unlimited', 'Mensajes Ilimitados', 'Unlimited Messages', 'Messages Illimités', 'Messaggi Illimitati', 'Unbegrenzte Nachrichten', 'Sin límite de 30 mensajes/día', 'No 30 messages/day limit', 'Pas de limite de 30 messages/jour', 'Nessun limite di 30 messaggi/giorno', 'Kein Limit von 30 Nachrichten/Tag', '♾️', 'premium', ARRAY['unlimited_daily_messages'], 1.99, 1.99, 35, 7900, 2.69, 16)
ON CONFLICT (id) DO NOTHING;

-- PACKS
INSERT INTO public.skill_packs (id, name_es, name_en, name_fr, name_it, name_de, description_es, description_en, description_fr, description_it, description_de, skill_ids, price_eur, price_usd, price_mxn, price_cop, price_cad, discount_percent, sort_order) VALUES
('pack_comunicacion', 'Pack Comunicación', 'Communication Pack', 'Pack Communication', 'Pack Comunicazione', 'Kommunikationspaket', 'WhatsApp + Redacción + Recordatorios', 'WhatsApp + Writing + Reminders', 'WhatsApp + Rédaction + Rappels', 'WhatsApp + Scrittura + Promemoria', 'WhatsApp + Schreiben + Erinnerungen', ARRAY['msg_whatsapp','writing','reminders'], 3.99, 3.99, 71, 15900, 5.49, 11, 1),
('pack_productividad', 'Pack Productividad', 'Productivity Pack', 'Pack Productivité', 'Pack Produttività', 'Produktivitätspaket', 'WhatsApp + Finanzas + Listas + Productividad', 'WhatsApp + Finance + Lists + Productivity', 'WhatsApp + Finances + Listes + Productivité', 'WhatsApp + Finanze + Liste + Produttività', 'WhatsApp + Finanzen + Listen + Produktivität', ARRAY['msg_whatsapp','finance','lists','productivity'], 4.99, 4.99, 89, 19900, 6.99, 28, 2),
('pack_familia', 'Pack Familia', 'Family Pack', 'Pack Famille', 'Pack Famiglia', 'Familienpaket', 'WhatsApp + Salud + Familia', 'WhatsApp + Health + Family', 'WhatsApp + Santé + Famille', 'WhatsApp + Salute + Famiglia', 'WhatsApp + Gesundheit + Familie', ARRAY['msg_whatsapp','health','family'], 3.99, 3.99, 71, 15900, 5.49, 20, 3),
('pack_total', 'Pack Total', 'Total Pack', 'Pack Total', 'Pack Totale', 'Totalpaket', 'TODOS los skills incluidos', 'ALL skills included', 'TOUS les skills inclus', 'TUTTI gli skill inclusi', 'ALLE Skills enthalten', ARRAY['msg_whatsapp','msg_telegram','writing','reminders','finance','lists','voice','translator','tutor','health','family','travel','productivity','legal','ai_advanced','unlimited'], 9.99, 9.99, 179, 39900, 13.99, 60, 4)
ON CONFLICT (id) DO NOTHING;
